### ISSUE TITLE
您好，下载了您的百度网盘提供的YFCC15M数据集，对实验帮助非常的大，非常感谢，看您还提供了CC12M的下载方式，能否加个联系方式，邮箱或者vx之类的，您看是否方便提供下CC3M和CC12M数据集网盘下载链接。

### ISSUE THREAD

**Issue by anony-mous-rep** [AdamRain/YFCC15M_downloader#2]

**Comment by AdamRain** [comment]
实在不好意思呀，我也只下载了YFCC15M的数据，因为太耗时了，CC12M我也没有下载😅

**Comment by anony-mous-rep** [comment]
那cc3m的呢？咱可以加个联系方式吗？qq:1152987338



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月16日(周二) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AdamRain/YFCC15M_downloader] 您好，下载了您的百度网盘提供的YFCC15M数据集，对实验帮助非常的大，非常感谢，看您还提供了CC12M的下载方式，能否加个联系方式，邮箱或者vx之类的，您看是否方便提供下CC3M和CC12M数据集网盘下载链接。 (Issue #2)




 
实在不好意思呀，我也只下载了YFCC15M的数据，因为太耗时了，CC12M我也没有下载😅

**Comment by AdamRain** [comment]
😅也没有，我不是搞CV的，这个数据集也是合作论文的时候用了一下才下载的（结果也没用上😅）（已加）

**Comment by SoverMMM** [comment]
老哥最终有没有下载到YFCC-100M

**Comment by SoverMMM** [comment]
> 😅也没有，我不是搞CV的，这个数据集也是合作论文的时候用了一下才下载的（结果也没用上😅）（已加）

老哥能不能指导一下怎么下载，慢点也行

**Comment by AdamRain** [comment]
> > 😅也没有，我不是搞CV的，这个数据集也是合作论文的时候用了一下才下载的（结果也没用上😅）（已加）
> 
> 老哥能不能指导一下怎么下载，慢点也行

你可以在huggingface的dataset里下载这个数据集：https://huggingface.co/datasets/dalle-mini/YFCC100M_OpenAI_subset

**Comment by SoverMMM** [comment]
这是来自QQ邮箱的自动回复邮件。苗已经收到你的邮件！

**Comment by SoverMMM** [comment]
这是来自QQ邮箱的自动回复邮件。苗已经收到你的邮件！
