### ISSUE TITLE
Hello!!, I use the following command to download the data set. Although the download single data network speed is 10mb/s, but the network is unstable, and it keeps showing failure, could you please give me some advice,thanks!!

### ISSUE THREAD

**Issue by leo23ui** [AdamRain/YFCC15M_downloader#3]
img2dataset --url_list yfcc15m_clean_open_data_copy.json --input_format "tsv"\
         --url_col "url" --caption_col "caption" --output_format webdataset\
           --output_folder yfcc --processes_count 16 --thread_count 64 --image_size 256\
             --enable_wandb True

wandb:               total/count ▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:  total/failed_to_download ██▁▃▄▅▅▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
wandb:    total/failed_to_resize ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:         total/img_per_sec ▁▃▅▅▆▆▆▇▇▇▇▇▇▇█▇▇▇█▇█▇▇█████████████████
wandb:             total/success ▁▁█▆▅▄▄▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
wandb:              worker/count ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: worker/failed_to_download ▇▁▆▆▆▆▄▅▂▇▆▃█▆▅▂▂▆▅▅▅▇▅▄▅▆▅▆▄▅▅▅▄▆▆▅▅▃▅▅
wandb:   worker/failed_to_resize ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:        worker/img_per_sec ▇▆▂█▇▅▁▆██▆▆██▆▇▄▅▁▅▇▇▆▆▇█▇█▆▆▇▆▆█▇▆█▇▆█
wandb:            worker/success ▂█▃▃▃▃▅▅▇▂▃▆▁▃▅▇▇▃▄▄▅▂▅▅▅▃▄▃▅▅▄▅▅▃▃▄▅▆▄▅
wandb:
wandb: Run summary:
wandb:               total/count 2150000
wandb:  total/failed_to_download 0.99865
wandb:    total/failed_to_resize 0.0
wandb:         total/img_per_sec 313.88765
wandb:             total/success 0.00135
wandb:              worker/count 10000
wandb: worker/failed_to_download 0.9996
wandb:   worker/failed_to_resize 0.0
wandb:        worker/img_per_sec 22.83228
wandb:            worker/success 0.0004

**Comment by leo23ui** [comment]
could you please give me some advice on how to download on linux using baidu netdisk, thanks!!

**Comment by AdamRain** [comment]
You can use Huggingface's datasets package to download: [here](https://huggingface.co/datasets/dalle-mini/YFCC100M_OpenAI_subset)

If you are using Baidu Netdisk, you could transfer each file to your cloud storage and then download it one by one.

I know it keeps showing failure; it happened to me, too (Campus Network). Therefore, I split the download task and used multi-computers (with different IP addresses) to download it simultaneously.

**Comment by leo23ui** [comment]
> You can use Huggingface's datasets package to download: [here](https://huggingface.co/datasets/dalle-mini/YFCC100M_OpenAI_subset)
> 
> If you are using Baidu Netdisk, you could transfer each file to your cloud storage and then download it one by one.
> 
> I know it keeps showing failure; it happened to me, too (Campus Network). Therefore, I split the download task and used multi-computers (with different IP addresses) to download it simultaneously.

thanks for reply very much!! i download the dataset by bypy successfully!! have a good day!!
