### ISSUE TITLE
Hello, I used BaiduNetdisk to download the dataset, but found only pictures, no txt file format notes, I want to achieve the following data format. Can I use the url and caption of the json file to compare and then generate txt files, but it needs to generate 16 parts of txt files, or merge 16 folders of pictures to regenerate one txt file? Could you provide a better way? Thank you!

### ISSUE THREAD

**Issue by leo23ui** [AdamRain/YFCC15M_downloader#4]
The expected format is a series of .tar files. Each of these .tar files should contain two files for each training example, one for the image and one for the corresponding text. Both files should have the same name but different extensions. For instance, split_01.tar could contain files such as abc.jpg and abc.txt.

**Comment by AdamRain** [comment]
> The expected format is a series of .tar files. Each of these .tar files should contain two files for each training example, one for the image and one for the corresponding text. Both files should have the same name but different extensions. For instance, split_01.tar could contain files such as abc.jpg and abc.txt.

The captions are contained in the .json file. You need to write your own extraction method or enable your method to read JSON files.

**Comment by AdamRain** [comment]
> The expected format is a series of .tar files. Each of these .tar files should contain two files for each training example, one for the image and one for the corresponding text. Both files should have the same name but different extensions. For instance, split_01.tar could contain files such as abc.jpg and abc.txt.

You can use the yfcc15m_clean_open_data_filtered_split_x.json and write the extraction method to combine all text in these split files together, the image files and the texts in these split jsons are matched.

**Comment by leo23ui** [comment]
> > The expected format is a series of .tar files. Each of these .tar files should contain two files for each training example, one for the image and one for the corresponding text. Both files should have the same name but different extensions. For instance, split_01.tar could contain files such as abc.jpg and abc.txt.
> 
> You can use the yfcc15m_clean_open_data_filtered_split_x.json and write the extraction method to combine all text in these split files together, the image files and the texts in these split jsons are matched.

thanks very much!!

**Comment by leo23ui** [comment]
Hello, I divided yfcc15m into 16 parts, but dataset download too many files, compression failure , could you please give me some advice on how to solve this!! thanks



For instance, shard_001.tar could contain files such as abc.jpg and abc.txt...
tar -cvf shard_001.tar -bash: /usr/bin/tar: Argument list too long

**Comment by AdamRain** [comment]
> Hello, I divided yfcc15m into 16 parts, but dataset download too many files, compression failure , could you please give me some advice on how to solve this!! thanks
> 
> For instance, shard_001.tar could contain files such as abc.jpg and abc.txt... tar -cvf shard_001.tar -bash: /usr/bin/tar: Argument list too long

Sorry, I mean, maybe you may ask ChatGPT to help you write the code of the download-from-scratch you want?

**Comment by leo23ui** [comment]
> > Hello, I divided yfcc15m into 16 parts, but dataset download too many files, compression failure , could you please give me some advice on how to solve this!! thanks
> > For instance, shard_001.tar could contain files such as abc.jpg and abc.txt... tar -cvf shard_001.tar -bash: /usr/bin/tar: Argument list too long
> 
> Sorry, I mean, maybe you may ask ChatGPT to help you write the code of the download-from-scratch you want?
thanks very much, thanks for your reply!!!
