### ISSUE TITLE
Hello, how many are the txt and jpg of split_1? I found 979959 each, but why is the total number 1959919， hope to get your reply, thanks!!

### ISSUE THREAD

**Issue by leo23ui** [AdamRain/YFCC15M_downloader#5]
Hello, how many are the txt and jpg of split_1? I found 979959 each, but why is the total number 1959919

ls -l | grep -v '^d' | wc -l
1959919
ls -lR | grep -E '\.txt$' | wc -l
979959
ls -lR | grep -E '\.jpg$' | wc -l
979959

**Comment by leo23ui** [comment]
Could I add a social software to you? I would like to consult you about the download in detail, and I would like to invite you to drink a cup of milk tea， thanks!!!

**Comment by AdamRain** [comment]
> Hello, how many are the txt and jpg of split_1? I found 979959 each, but why is the total number 1959919
> 
> ls -l | grep -v '^d' | wc -l 1959919 ls -lR | grep -E '.txt$' | wc -l 979959 ls -lR | grep -E '.jpg$' | wc -l 979959

979959+979959=1959918？
Each split(1-15) contains 917759 image-text pairs. The extra file is probably a Python file or a System file.
